# Generated by Django 5.2 on 2025-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehash',
            name='filename',
            field=models.TextField(default='unnamed'),
            preserve_default=False,
        ),
    ]
