# Generated by Django 5.2 on 2025-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_imagehash_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='img_hash',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
