# Generated by Django 5.2 on 2025-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_imagehash_img_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='filename',
            field=models.TextField(default=None),
        ),
    ]
